name: ezbloc_flutter_example
description: Making blocs easy again. A simplified library for the original bloc approach.
version: 0.3.10
homepage: https://github.com/MohiuddinM/ezbloc_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  no_bloc_flutter: ^0.8.1
  path_provider: ^1.0.0
  path: ^1.0.0

dev_dependencies:
  test: ^1.6.0
  flutter_test:
    sdk: flutter

flutter: