name: ezbloc_flutter_example
description: Making blocs easy again. A simplified library for the original bloc approach.
version: 0.3.10
homepage: https://github.com/MohiuddinM/ezbloc_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ezbloc_flutter:
  path_provider: ^2.0.0
  path: ^1.0.0

dev_dependencies:
  test: ^1.0.0

flutter: