name: ezbloc_flutter
description: Making blocs easy again. A simplified library for the original bloc approach.
version: 0.8.0
homepage: https://github.com/MohiuddinM/ezbloc

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ezbloc: ^4.2.0
  rxdart: '>=0.26.0 <2.0.0'
  hive: ^2.0.0
  path: ^1.8.0
  quick_log: ^5.0.0
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter