name: ezbloc
description: Make bloc easy again! A simple and low boilerplate implementation of the bloc state management pattern. Includes extras to work with blocs like testing, monitoring and persistence.
version: 4.0.1
homepage: https://github.com/MohiuddinM/ezbloc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: '>=0.26.0 <2.0.0'
  hive: ^2.0.0
  path: ^1.0.0
  test: ^1.16.8
  meta: ^1.3.0
  pedantic: ^1.11.0
  quick_log: ^5.0.0
  stack_trace: ^1.10.0

dev_dependencies:
  mockito: ^5.0.0
  build_runner: ^1.12.2

